### ISSUE TITLE
Syntax Highlighting inside backticks

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/CoffeeScript#105]
You can use backticks to denote literal JavaScript blocks in CS.

What do you think about including javascript's syntax into the patterns so it highlights the code? The thing itself won't be hard, it's just a few lines more.

What I consider problematic is that some color schemes might not highlight source within source special, e.g. by changing the background color. The scheme I use (Twilight) defines something for `text source` but not `source source`.

``` yaml
name: "♦ Embedded Source"
scope: text source
settings:
  background: '#B0B3BA14'
```

---

Here is a preview what I made it look like:

![preview](http://i.imgur.com/BSHRGQC.png)

Steps:
1. Add this to your color scheme or assure there is a `source source` selector:
   
   ``` xml
   
         <dict>
             <key>name</key>
             <string>Embedded Source</string>
             <key>scope</key>
             <string>source source</string>
             <key>settings</key>
             <dict>
                 <key>background</key>
                 <string>#FFFFFF08</string>
             </dict>
         </dict>
   ```
2. Change line 148-9 in `CoffeeScript.tmLanguage` from:
   
   ``` xml
             <key>name</key>
             <string>string.quoted.script.coffee</string>
   ```
   
   to:
   
   ``` xml
             <key>name</key>
             <string>source.js</string>
   ```
3. Add this after line 157:
   
   ``` xml
   
                 <dict>
                     <key>include</key>
                     <string>source.js</string>
                 </dict>
   ```

**Comment by yashghelani** [comment]
![screen shot 2017-09-27 at 4 44 18 pm](https://user-images.githubusercontent.com/26831728/30910761-b50037ec-a3a3-11e7-918d-1cca86c60d5c.png)
This issue still hasn't been fixed. I'm using the Flatland theme on Sublime Text 3 with Monokai as my color scheme
