### ISSUE TITLE
Incorret syntax highlight after regexp

### ISSUE THREAD

**Issue by szyman** [SublimeText/CoffeeScript#215]
``` javascript
.replace(/\\/g,"/")
```

Below this line the rest are recognized as string. 
Please look at attached screenshot.

![syntax bug](https://cloud.githubusercontent.com/assets/2345618/7908983/5ddf5e7c-0849-11e5-852e-a668580ee764.jpg)

**Comment by icflorescu** [comment]
Nice catch. Until this gets fixed, you can use the CoffeeScript heregex syntax: `.replace(///\\///g,"/")`. Uglier, but it doesn't mess up the syntax highlighting.
