### ISSUE TITLE
CoffeeScript (Literate Plus) 

### ISSUE THREAD

**Issue by SusanthCom** [SublimeText/CoffeeScript#224]
Hi,

This is my humble suggestion to improve current implementation of this Package.

As of now, in **literate mode** , the literate markup is highlighted in bright white which make it hard to distinguish between source code and markdown code. ( though not for all :smile: )

It will be great, if the markup look similar to comment's Colouring scheme. This will help improved readability and better focus on code. There by more productivity for those who prefer that option.  :+1: 

Some one has already got similar demand :smile_cat:  and is having a fix :+1:  to achieve that >> 
- [ The Requirement ](https://www.reddit.com/r/SublimeText/comments/1nuyb9/sublime_text_theme_for_literate_coffeescript/)
-  [ The Fix ](https://github.com/bcherny/colour-schemes/commit/3e85272df6517b8c94289535c9f64a12d4aaa5d7)

Currently  upon clicking the highlight option in status bar at bottom right, shows two options like this ::

```
Better CoffeeScript >> CoffeeScript
                       CoffeeScript (Literate)
```

I would suggest to provide the new requested style to appear as  a third option named something like **CoffeeScript (Literate Plus)** . This helps to keep current and new implementation available so that the menu appears as mentioned below. 

```
Better CoffeeScript >> CoffeeScript
                       CoffeeScript (Literate)
                       CoffeeScript (Literate Plus)
```

Please view the attached images of Screen Shot of Current Implementation and Mockup of Proposed Requirement, for better visual clarity.

Thanks in advance. :+1: 

My special thanks to all contributors who invested time and efforts to make this worthy.  :+1: 

**Proposed Menu :: Mockup**
<img width="567" alt="new-menu" src="https://cloud.githubusercontent.com/assets/11663470/9475108/3a567310-4b82-11e5-8322-7723c1caab1a.png">

**Current Menu Screen Shot**
<img width="567" alt="current-menu" src="https://cloud.githubusercontent.com/assets/11663470/9475103/35615794-4b82-11e5-8a5b-f04ae1dc1b11.png">

**Proposed Highlight :: Mockup** . 
Please note the text **"Marked"** inside markdown ( **line number: 155** ) remains yellow in colour. please keep it so if possible :+1: 
![new-sample](https://cloud.githubusercontent.com/assets/11663470/9475127/59eb4548-4b82-11e5-81c8-1e96a3f2ba20.png)

**Current Highlight Screen Shot**
![current-sample](https://cloud.githubusercontent.com/assets/11663470/9475119/51af56da-4b82-11e5-8c95-765acc8935b5.png)

**Comment by deathaxe** [comment]
Syntax definitions assign scopes to each token.

It's up to color schemes to assign colors.

This package does not provide color schemes.

The following rule would tint non-coffeescript content gray, which is not otherwise addressed by more specific color scheme rules.

```
{
	"scope": "source.litcoffee - source.coffee.embedded",
	"foreground": "#AAA"
},
```
