### ISSUE TITLE
Please update for CS v2.0

### ISSUE THREAD

**Issue by mrmowgli** [SublimeText/CoffeeScript#243]
Coffeescript is releasing a new version (2.0 Alpha) that includes many of the ES6/ES2015+ features.

Please see [the CS6 Planning pages.](https://github.com/coffeescript6/discuss/issues/71)

Key differences are that this will output unshimmed ES2015+ features, and will likely need to have support for Babel in the browser build process.  
 
Also note that this is in ALPHA, so projects are encouraged to try it out and report back.

**Comment by auvipy** [comment]
what is the current update of the project?

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2 has been out for a few years. `sublime-better-coffeescript` works just fine with it. Other than some keywords missing highlighting (`import`, `export`, `async`) this plugin doesn’t need much updating as far as I can tell.

**Comment by auvipy** [comment]
I will look and send PR where needed
