### ISSUE TITLE
NEED NEW MAINTAINER - PLEASE POST HERE

### ISSUE THREAD

**Issue by aponxi** [SublimeText/CoffeeScript#244]
I haven't used CoffeeScript for years and don't update this repository anymore. 

If there's a soul out there who is enthusiastic about CoffeeScript in Sublime Text and would like to patch this plugin, please comment here and I'll add you as a collaborator.

I'm looking for someone who is active in the open source community on GitHub and is proficient in Python.

**Comment by GeoffreyBooth** [comment]
I’m not proficient in Python, but I’m one of the core contributors of CoffeeScript and I’m eager to get this package to provide better syntax highlighting for [CoffeeScript 2](http://coffeescript.org/v2/) 😄 I’m also happy to be a caretaker until a more qualified maintainer steps up.

**Comment by aponxi** [comment]
Thanks for stepping up, @GeoffreyBooth ! Let me know if you need any help and if there's a developer who wants to support this project, please post here.

**Comment by GeoffreyBooth** [comment]
How does deploying top the sublime package manager work? It's pushing to master sufficient?

**Comment by aponxi** [comment]
Go through the process of tagging (with the semver format like the other "Releases") and then merging to master.

- Any changes made to `master` are automatically available for Sublime Text 3
- Any changes made to `st2` branch are for Sublime Text 2

Make sure you update changelog, version number and those sorts of things. There is a ton of information at [Package Manager Docs](https://packagecontrol.io/docs)

Check these two out:

- https://packagecontrol.io/docs/submitting_a_package
- https://github.com/wbond/package_control_channel/blob/master/repository/b.json#L460-L472

Let me know if you have any questions!

**Comment by seanCodes** [comment]
Hey @aponxi or @GeoffreyBooth! Still looking for maintainers? I’m also not the most proficient at python but I’m passionate about Sublime and I’d love to help get the syntaxes ported to sublime-syntax. Let me know!

**Comment by FichteFoll** [comment]
FYI, the package has been migrated into the SublimeText org with no changes, so that at least some people are able to merge pull requests. However, we're still looking for a dedicated maintainer. 

(Since the package is quite old, a rewrite of the syntax definitions in sublime-syntax would be much appreciated.)
