### ISSUE TITLE
Add support for Sublime Text 4 (build 4121)

### ISSUE THREAD

**Issue by reubano** [SublimeText/CoffeeScript#250]
When I run it I get the error: `target of repeat operator is invalid in regex`

**Comment by taneltm** [comment]
Same issue here :(

**Comment by taneltm** [comment]
Found a temporary workaround.

1. Open a CoffeeScript file
2. Make sure the syntax is set to [ Better CoffeeScript -> CoffeeScript ] even tho it doesn't work
3. From the menu, select [ Tools -> Developer -> New Syntax from CoffeeScript.tmLanguage.... ]
  * The XML based language definition file will be converted to YAML
  * You can change `name: CoffeeScript` to something else, like `name: CoffeeScript-alt`, so you don't get confused
4. Ctrl+S to save the file to the recommended directory
5. Re-open your CoffeeScript file and it should be using the new syntax definition which doesn't have the regex issue.
