### ISSUE TITLE
interpolated coffeescript strings disable moving between matching quotes

### ISSUE THREAD

**Issue by canoeberry** [SublimeText/CoffeeScript#255]
Here is an example of a string, which Sublime Text highlights properly. You can see the underscores at the beginning and end. And using BracketHighlighter I can move from one side to the other.

![image](https://github.com/user-attachments/assets/fae61024-230c-4bd1-8260-3f16b88f3689)

With this string all that breaks. No matching quotes, and no ability to move over the entire string. This worked until recently but maybe I was using a different version of coffeescript.

![image](https://github.com/user-attachments/assets/f5ddab16-4997-47a5-a6d0-09b9f548f17b)

While inside the string near the curly brace, you can see normal matching works once again, with the underscores properly matching both sides of the expression.

![image](https://github.com/user-attachments/assets/b57fae95-0c44-49b2-bac1-cf4c7cab8ef2)

**Comment by deathaxe** [comment]
The strategy to clear `string` scope in interpolations is common practice accross all syntax definitions. 

It is within BracketHighlighter's scope/responsibility to handle interpolated strings. It should always check for `meta.string | string` scopes to detect strings.

You can teach it doing so by adding following rules. Maybe file a PR or ask BH's author to add them as default rules.

```json
"user_scope_brackets": [
	{
		"name": "coffee_double_quote",
		"open": "(\")",
		"close": "(\")",
		"style": "double_quote",
		"scopes": ["meta.string", "string"],
		"language_filter": "allowlist",
		"language_list": [
			"CoffeeScript"
		],
		"sub_bracket_search": "true",
		"enabled": true
	},
	{
		"name": "coffee_single_quote",
		"close": "(')",
		"open": "(')",
		"style": "single_quote",
		"scopes": ["meta.string", "string"],
		"language_filter": "allowlist",
		"language_list": [
			"CoffeeScript"
		],
		"sub_bracket_search": "true",
		"enabled": true
	}
]
```

**Comment by canoeberry** [comment]
I didn't realize it was bracket highlighter that was doing the highlighting of quotes.

Thanks!
