### ISSUE TITLE
'coffee' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by arman-mchitaryan** [SublimeText/CoffeeScript#46]
I know this is not something directly related with this package but anyway I'm new to Sublime Text so any help will be great. Looks like the app can't locate to the correct dir to run the command and it probably should be fixed through the Environment Variables. I just don't know what location should I point to?
Looking for coffee.bat or .exe and can't find one.

Windows 7
Sublime Text 2

**Comment by skImranSabuj** [comment]
@nborko Hi!
I'm facing this **'coffee.cmd' is not recognized as an internal or external command,
operable program or batch file.** issue 
I have installed coffeescript globally but nothing works
